version: "3"

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - innovation-node_modules:/workspace/frontend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - windir # Defined on Windows but not on other platforms
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "5433:5433"
    volumes:
      - innovation-postgres:/var/lib/postgresql/data

volumes:
  innovation-node_modules:
  innovation-postgres:
